### DISCUSSION TITLE
Discussion on Report Gen dev

### DISCUSSION THREAD

**Discussion by 0xbharath** [PhonePe/mantis#59] [Development]
@devplayer55221 

1. This should be a block in the common config file `mantis/configs/local.yml`

```
report:
  title: "Attack Surface Management Report" 
  author: "John Doe"
  date: "2024-09-30"
  header: "Confidential - For Internal Use Only"
  footer: "Company XYZ - All Rights Reserved"
  format: "pdf"
```

2. Add the following command to mantis cli

```
mantis report -o sample_org 
```

When the above command is run, pick the report block from mantis/configs/local.yml and convert it to python dictionary and print

```
report = {
    "title": "Attack Surface Management Report",
    "author": "John Doe",
    "date": "2024-09-30",
    "header": "Confidential - For Internal Use Only",
    "footer": "Company XYZ - All Rights Reserved",
    "format": "pdf",  # Output format (pdf, html, md, json etc.)
    "theme": "dark"   # Report theme (dark, light)
}
```
